config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders

  root to: 'orders#index'


end

app/models/order.rb
class Order < ActiveRecord::Base

	validates :poNumber, :date, :contact, :amount, :targetDate, :unitCount,  presence: true


end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  semantic_breadcrumb :index, :root_path
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order_item, only: [:show, :edit, :update, :destroy]

  # GET /order_items
  # GET /order_items.json
  def index
    @order_items = OrderItem.all
  end

  # GET /order_items/1
  # GET /order_items/1.json
  def show
  end

  # GET /order_items/new
  def new
    @order_item = OrderItem.new
  end

  # GET /order_items/1/edit
  def edit
  end

  # POST /order_items
  # POST /order_items.json
  def create
    @order_item = OrderItem.new(order_item_params)

    respond_to do |format|
      if @order_item.save
        format.html { redirect_to @order_item, notice: 'Order item was successfully created.' }
        format.json { render :show, status: :created, location: @order_item }
      else
        format.html { render :new }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_items/1
  # PATCH/PUT /order_items/1.json
  def update
    respond_to do |format|
      if @order_item.update(order_item_params)
        format.html { redirect_to @order_item, notice: 'Order item was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_item }
      else
        format.html { render :edit }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.json
  def destroy
    @order_item.destroy
    respond_to do |format|
      format.html { redirect_to order_items_url, notice: 'Order item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(:order_ID, :item_code, :item_description, :quantity, :unit, :sub_total)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:poNumber, :date, :contactID, :amount, :unitCount, :targetDate, :accepted, :ready, :dispatched, :delivered, :invoiced, :invoiceNumber, :aid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EngieManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="ui container">
		<div class="ui segments">
			<div class="ui segment">
				<%= yield %>
			</div>
		</div>
	</div>

</body>
</html>

app/views/order_items/_form.html.erb
<%= form_for(@order_item) do |f| %>
  <% if @order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
      <% @order_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_ID %><br>
    <%= f.number_field :order_ID %>
  </div>
  <div class="field">
    <%= f.label :item_code %><br>
    <%= f.text_field :item_code %>
  </div>
  <div class="field">
    <%= f.label :item_description %><br>
    <%= f.text_field :item_description %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :sub_total %><br>
    <%= f.text_field :sub_total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

app/views/order_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Order Items</h1>

<table>
  <thead>
    <tr>
      <th>Order id</th>
      <th>Item code</th>
      <th>Item description</th>
      <th>Quantity</th>
      <th>Unit</th>
      <th>Sub total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.order_ID %></td>
        <td><%= order_item.item_code %></td>
        <td><%= order_item.item_description %></td>
        <td><%= order_item.quantity %></td>
        <td><%= order_item.unit %></td>
        <td><%= order_item.sub_total %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order item', new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form' %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order id:</strong>
  <%= @order_item.order_ID %>
</p>

<p>
  <strong>Item code:</strong>
  <%= @order_item.item_code %>
</p>

<p>
  <strong>Item description:</strong>
  <%= @order_item.item_description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_item.quantity %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @order_item.unit %>
</p>

<p>
  <strong>Sub total:</strong>
  <%= @order_item.sub_total %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>

app/views/orders/_form.html.erb
<div class="ui segment">
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="ui form">
    <div class="field">
      <label>P.O. Number</label>
      <input type="text" name="order[poNumber]" id="order_poNumber" placeholder="Purchase Order Number">
    </div>
    <div class="three fields">
      <div class="date field">
        <label>Date</label>
        <input type="text" id="datepicker">
      </div>
      <div class="date field">
        <label>Target Date</label>
        <input type="text" id="datepicker">
      </div>
    </div>
    <div class="field">
      <label>Contact</label>
      <input>
    </div>
    <div class="field">
      <label>Amount</label>
      <input>
    </div>
    <div class="field">
      <label>Unit</label>
      <input>
    </div>
  </form>
</div>

<h4 class="ui dividing header"></h4>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="ui center aligned header">
  <h1 class="ui center aligned header">Listing Orders</h1>
</div>
<div class="ui segment">

  <p id="notice"><%= notice %></p>

  

  <table class="ui celled striped table">
    <thead>
      <tr>
        <th>PO Number</th>
        <th>Date</th>
        <th>Contact</th>
        <th>Amount</th>
        <th>Unit's</th>
        <th>Target Date</th>
        <th>Accepted</th>
        <th>Ready</th>
        <th>Dispatched</th>
        <th>Delivered</th>
        <th>Invoiced</th>
        <th>Invoice Number</th>
        <th>Paid</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.poNumber %></td>
          <td><%= order.date %></td>
          <td><%= order.contactID %></td>
          <td><%= order.amount %></td>
          <td><%= order.unitCount %></td>
          <td><%= order.targetDate %></td>
          <td><%= order.accepted %></td>
          <td><%= order.ready %></td>
          <td><%= order.dispatched %></td>
          <td><%= order.delivered %></td>
          <td><%= order.invoiced %></td>
          <td><%= order.invoiceNumber %></td>
          <td><%= order.aid %></td>
          <td><%= link_to 'Show', order %></td>
          <td><%= link_to 'Edit', edit_order_path(order) %></td>
          <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Order', new_order_path, :class => "ui primary button" %>
</div>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ponumber:</strong>
  <%= @order.poNumber %>
</p>

<p>
  <strong>Date:</strong>
  <%= @order.date %>
</p>

<p>
  <strong>Contactid:</strong>
  <%= @order.contactID %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @order.amount %>
</p>

<p>
  <strong>Unitcount:</strong>
  <%= @order.unitCount %>
</p>

<p>
  <strong>Targetdate:</strong>
  <%= @order.targetDate %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @order.accepted %>
</p>

<p>
  <strong>Ready:</strong>
  <%= @order.ready %>
</p>

<p>
  <strong>Dispatched:</strong>
  <%= @order.dispatched %>
</p>

<p>
  <strong>Delivered:</strong>
  <%= @order.delivered %>
</p>

<p>
  <strong>Invoiced:</strong>
  <%= @order.invoiced %>
</p>

<p>
  <strong>Invoicenumber:</strong>
  <%= @order.invoiceNumber %>
</p>

<p>
  <strong>Aid:</strong>
  <%= @order.aid %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>